### ISSUE TITLE
Move MATSim config files from v1 to v2

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees#11]
_From @dhixsingh on August 1, 2018 2:48_

Most of the matsim config .xml files in `examples/bushfire/*` use DTD [config version 1](http://www.matsim.org/files/dtd/config_v1.dtd). These should all be updated to [config version 2]http://www.matsim.org/files/dtd/config_v2.dtd). 

MATSim otherwise generated the following warning at runtime:

`WARN ConfigReaderMatsimV1.java:58 using deprecated config version; please switch to config v2; your output_config.xml will be in the correct version; v1 will fail eventually, since we want to reduce the workload on keeping everything between v1 and v2 consistent (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
`

_Copied from original issue: agentsoz/bdi-abm-integration#38_

**Comment by dhixsingh** [comment]
@osbornejr is this done now?

**Comment by osbornejr** [comment]
This hasn't happened yet, should be an easy switch though- I can do it when I am on my other laptop.

**Comment by osbornejr** [comment]
Fixed as of 4d9e28c444540fc1839c086de6877e8071c987df.
