### ISSUE TITLE
Select dependent location based on locality

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/ees#22]
Currently in [BDI_attributes.R](
      ees/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/BDI_attributes.R
    ) the location for a dependent is selected randomly from within a 20 km radius of the agent's home. This should be updated to use the same locality method that the plan algorithm uses.

Ideally this can also happen for invac and evac options, i.e. invac options are always within locality, and evac options are not.

Requires home locality to be ported from plan-algorithm, or potentially some other mechanism to identify an x-y coordinate's locality.

**Comment by dhixsingh** [comment]
@osbornejr is this done now?

**Comment by osbornejr** [comment]
No, this has not changed from the random selection process. Will do this when I update the algorithm to work with the latest locations data+format from SCSC, because both the dependent and the invac/evac location choices should depend on locality.

**Comment by osbornejr** [comment]
The dependent location is still selected randomly within a 20km radius of the agent's `home`. 

Would perhaps be improved with more dynamic dependent assignment (via the archetypes), but closing now because this would require more data/information.
