### ISSUE TITLE
Create realistic summer weekday population with Surf Coast Shire Council

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/ees#23]
The task is to update examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/typical summer weekday/* input files so that they more accurately reflect the population and its activities on a typical summer weekday. To be done together with Surf Coast Shire Council.

Part of the task is also to calibrate traffic flow at key locations based on available traffic counts from VicRoads and the Shire. What should be possible is to achieve a relative flow distribution that compares to the traffic count data.

**Comment by osbornejr** [comment]
Need to get traffic flow information from SCS and manipulate the input distributions to try and match the observed flows, whilst still maintaining reasonable daily plan structures.

**Comment by osbornejr** [comment]
Still need to get traffic count data from Pete to validate/improve the synthetic population's plans.

**Comment by dhixsingh** [comment]
A side project is underway for this now, so won't track it here.
