### ISSUE TITLE
Tidy up diffusion model logs

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees#32]
Currently any test that uses the diffusion model such as below,

https://github.com/agentsoz/ees/blob/3f42aafc4cf172de6f8227577b84d9ae37268b45/scenarios/surf-coast-shire/population-subgroups-sample/ees.xml#L96-L100

creates `diffusion.log` and `diffusion.out` output files in the repository root.

[`DiffusionModel`](https://github.com/agentsoz/ees/blob/e944f2934ffe6f35f716b671ad4f8715f12da75b/src/main/java/io/github/agentsoz/ees/DiffusionModel.java) should be updated to allow the location of these files to be specified, similar to this:

https://github.com/agentsoz/ees/blob/3f42aafc4cf172de6f8227577b84d9ae37268b45/scenarios/surf-coast-shire/population-subgroups-sample/ees.xml#L53-L54

All tests should then be updated so that no diffusion log files are generated in the repository root, but are instead placed in appropriate test-specific directories (same location as Jill logs). 

@chambul if you could please do this on a branch and create a pull request when ready.

**Comment by chambul** [comment]
@dhixsingh Done. You can find the pull request here: https://github.com/agentsoz/ees/pull/33
