### ISSUE TITLE
Use agentsoz dependencies as submodules

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees#46]
Currently the build can break if one of the agenstoz dependency repositories is updated. To prevent that, those repositories should be included as submodules so that there is better control on the versions being built and included.

**Comment by danhphan** [comment]
Hi @dhixsingh 
I have tried to build this ees project as the guidline. At this step: mvn package, it show this error:

[INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/license-maven-plugin/2.0.0/license-maven-plugin-2.0.0.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/license-maven-plugin/2.0.0/license-maven-plugin-2.0.0.jar (503 KB at 560.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Diffusion Model .................................... SUCCESS [03:10 min]
[INFO] io.github.agentsoz:jill-project .................... SUCCESS [04:11 min]
[INFO] io.github.agentsoz:jill ............................ SUCCESS [03:33 min]
[INFO] io.github.agentsoz:jill-examples ................... SUCCESS [ 11.263 s]
[INFO] io.github.agentsoz:jill-extension-template ......... SUCCESS [  2.875 s]
[INFO] BDI ABM Integration ................................ FAILURE [  4.485 s]
[INFO] Util ............................................... SKIPPED
[INFO] BDI ABM Integration ................................ SKIPPED
[INFO] ABM JILL Integration ............................... SKIPPED
[INFO] BDI MATSim Integration ............................. SKIPPED
[INFO] Emergency Evacuation Simulator Library ............. SKIPPED
[INFO] Emergency Evacuation Simulator ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:16 min
[INFO] Finished at: 2020-08-13T13:56:42+10:00
[INFO] Final Memory: 65M/4096M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:update-project-license (first) on project bdi-abm-integration: The plugin org.codehaus.mojo:license-maven-plugin:2.0.0 requires Maven version 3.5.4 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :bdi-abm-integration


**The system configuration I use is:**
Ubuntu 20.04 (run in Windown 10), java 11, maven 3.3.9
$javac --version
javac 11.0.8
$java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
$mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:41:47+11:00)
Maven home: /mnt/c/Program Files/Java/apache-maven-3.3.9
Java version: 11.0.8, vendor: Ubuntu
Java home: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-18362-microsoft", arch: "amd64", family: "unix"

**To me the error may stem from different version of maven.**
Do you have a suggestion for this? 

Thank you for your help.

Danh

**Comment by dhixsingh** [comment]
@danhphan you mention that you are using maven `3.3.9`, and your error message says 

```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:update-project-license 
(first) on project bdi-abm-integration: The plugin org.codehaus.mojo:license-maven-plugin:2.0.0 
requires Maven version 3.5.4 -> [Help 1]
```

So yes that would suggest you should update your maven version.

I have also updated the CI script to test on `ubuntu-20.04` (with `Java 11.0.2` and `Maven 3.6.3`) and it builds and runs ok (see [log](https://github.com/agentsoz/ees/runs/982576433)).

**Comment by captainnemo2005** [comment]
Probably your submodule download has some prob. 
Pls delete the folder and start the process again and it will work nicely. 
Thanks @dhixsingh  for your quick reply

**Comment by danhphan** [comment]
Thanks @dhixsingh and @captainnemo2005 

I change to Maven 3.6.3 (java 11 on ubuntu 20.04) and it builds sucessfully now.

Best regards,

Danh
