### ISSUE TITLE
Compilation error in jill submodule

### ISSUE THREAD

**Issue by srodriguez** [agentsoz/ees#50]
When compiling ees, jill submodule (0.4.1-SNAPSHOT) fails to compile.

### Environment
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Java version: 1.8.0_282, vendor: AdoptOpenJDK, 
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by dhixsingh** [comment]
@srodriguez try with Java 11. You can see the build setup we use [here](https://github.com/agentsoz/ees/blob/master/.github/workflows/ci.yml).
