### ISSUE TITLE
Change license from LGPL3 to MIT

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/ees#59]
To encourage more permissive use of the code in this repository, we would like to move the license from LGPL3 over to MIT. This does not revoke the previous license but adds a more permissive license for future use.

@sperera, @kainagel, @osbornejr, @chambul, @gden173, @gwehr1, are you happy for any code you contributed to in this repository to date to be licensed under MIT going forward? If you could please add your response in comments below.

Thanks!

**Comment by gden173** [comment]
Hi @dhixsingh,

I have no issues with changing the licence to MIT.

**Comment by chambul** [comment]
Hi @dhixsingh,  I am fine with moving the license to MIT.

**Comment by osbornejr** [comment]
Hi @dhixsingh , sounds good to me, happy for the licence to change.

**Comment by gwehr1** [comment]
Hi @dhixsingh, I'm also happy for the license to be changed.

**Comment by kainagel** [comment]
Not sure if there is code from me in this repo but if there is it is ok to change its license.

**Comment by sperera** [comment]
Hi @dhixsingh, I'm fine wih moving the license.

**Comment by dhixsingh** [comment]
Great, thanks all.
